spec:
  template:
    spec:
      containers:
      - name: loadbalancer
        volumeMounts:
        - mountPath: /opt/bitnami/nginx/conf/server_blocks/opendata
          name: ckan-conf
      volumes:
      - name: ckan-conf
        configMap:
          name: ckan-config
