spec:
  template:
    spec:
      containers:
      - name: loadbalancer
        volumeMounts:
        - mountPath: /opt/bitnami/nginx/conf/server_blocks/api
          name: advapimng-conf
      volumes:
      - name: advapimng-conf
        configMap:
          name: advapimng-config
