spec:
  template:
    spec:
      containers:
      - name: loadbalancer
        volumeMounts:
        - mountPath: /opt/bitnami/nginx/conf/server_blocks/im
          name: advim-conf
      volumes:
      - name: advim-conf
        configMap:
          name: advim-config
