spec:
  template:
    spec:
      containers:
      - name: loadbalancer
        volumeMounts:
        - mountPath: /opt/bitnami/nginx/conf/server_blocks/tools
          name: bsnstools-conf
      volumes:
      - name: bsnstools-conf
        configMap:
          name: bsnstools-config
